### ISSUE TITLE
Render Siema To Hidden Selector

### ISSUE THREAD

**Issue by woodser** [pawelgrzybek/siema#120]
Is it possible to render Siema to a hidden selector?

I'd like to load the contents of the page fully, then show it.

Unfortunately the result is Siema's div is collapsed with all content on top of each other unless the selector it renders to is attached to the DOM and shown.

Thanks for your help.

**Comment by pawelgrzybek** [comment]
CodePen, jsFiddle, jsBin... Please :-(

**Comment by woodser** [comment]
Here you are: https://jsfiddle.net/xxpn5ags/

**Comment by pawelgrzybek** [comment]
Hi.

This is totally expected behaviour. During initialisation Siema grabs some values (width) from a container (that in your case doesn't exists in a DOM). It collapses all slides because it thinks that the width is `0` or `null`.

Solution would be:

1. Create a invisible div for Siema (with `opacity: 0;` for example)
2. `new Siema()` blah blah blah…
3. `onInit() { /* opacity: 1 */ }`

Hopefully it makes sense to you. Have a great day 🥑

**Comment by woodser** [comment]
Ok.  Thanks!

**Comment by Frique** [comment]
Besides the `opacity: 0` I also hide every slide after the first, to prevent a height jump after loading. The `.-ready` class is added in the `onInit()`:

```
.siema > * + * {
  display: none;
}
.siema.-ready > * + * {
  display: block;
}
```
