### ISSUE TITLE
Siema call makes carousel invisible if element has not yet been inserted into the page

### ISSUE THREAD

**Issue by e-compton** [pawelgrzybek/siema#127]
Hi, I'm working on an app that needs to construct carousels and insert them into the DOM dynamically. It would be really useful if the Siema call could be made before the element is inserted into the page. 

Right now it seems to be inserting some of the html into the page, but the content isn't visible.

https://codepen.io/anon/pen/xpBXvy

update: I've just noticed that if you resize the page (vertically or horizontally) the carousel zooms into view and works correctly

**Comment by pawelgrzybek** [comment]
Hi.

Carousel to correctly initialise needs to take some values from the DOM. Because your markup doesn't exists it cannot grab any values from — in this case, thats why it is collapsed to `0` width & height.

If you really have to, this can solve the issue, but it is not the order that you should build your project I'm afraid.

```js
document.querySelector('.wrapper').appendChild(yo);
mySiema.resizeHandler();
```

Thanks and have a great day.
