### ISSUE TITLE
Bounce effect on first and last element on siema

### ISSUE THREAD

**Issue by ashsepra** [pawelgrzybek/siema#140]
Hi,

I want to know how to prevent bounce effect on first and last element on siema? Is it possible to remove swipe left event when siema active on first element and remove swipe right event when siema active on last elemet?

**Comment by pawelgrzybek** [comment]
Hi.

Unfortunately it isn't possible from the API level and it wont be. You can add your current swipe implementation that is hooked to Siema API if you really need. Sorry for bad news. Under the hood something that Siema is doing is recalculating the position of a current slide and you can see a bounce because there is a CSS transition added on a container. Personally i like this effect :)

Have a great weekend and thanks for using Siema :)

**Comment by lifeinchords** [comment]
Hi there,

Great library, thank you for open sourcing it.

We found this effect really distracting in our user testing. Do you have any suggestions or info how we can add a hack to disable it? I don't understand what you mean

```You can add your current swipe implementation that is hooked to Siema API if you really need```

Much appreciated,

**Comment by beinoriusju** [comment]
Here is how I stop Siema from exceeding container. I would really love to see @pawelgrzybek approach on solving this, maybe on next release? Thanks for great tool anyway, 

```
      if (this.config.bounce) {
        this.sliderFrame.style[this.transformProperty] = `translate3d(${vector * offset}px, 0, 0)`;
      }
      else {
        const offsetMin = 0;
        const offsetMax = vector * (this.sliderFrame.clientWidth - this.selectorWidth);

        if (offset <= offsetMin) {
          this.sliderFrame.style[this.transformProperty] = `translate3d(${offsetMin}px, 0, 0)`;
        }
        else if (Math.abs(offset) >= Math.abs(offsetMax)) {
          this.sliderFrame.style[this.transformProperty] = `translate3d(${offsetMax}px, 0, 0)`;
        }
        else {
          this.sliderFrame.style[this.transformProperty] = `translate3d(${vector * offset}px, 0, 0)`;
        }
      }
```
