### ISSUE TITLE
Add resizeHandler to public API documentation

### ISSUE THREAD

**Issue by adiulici** [pawelgrzybek/siema#141]
I ran into a common problem for which, I just noticed, you have a codepen: "update size on container size change". I needed to reset Siema when the container size updated.

Since this is a pretty common use case, I think the `resetHandler` method should be added to the public API from the documentation. I have two reasons to say this:
1. Since I did not found it in the documentation, I had to dig into the code a bit and see if there something like this available. It was easy and I found it, there was no problem, but for such a common use case it would be nice if we could find this directly in the documentation.
2. Even though I found the solution in the code, since it's not in the public API documentation you wrote, I was a bit hesitant to use it. Since it's not in the public API, you could change it anytime I thought, and I could run into problems. 

I noticed later your codepen where you are using it, so I guess you probably won't change the name, but I still think it would come easier to just add it to the documentation. Also, I guess if you do decide to add it to the documentation `resizeHandler` isn't really an appropriate name. Maybe something like `reset`?

If you agree with what I said but don't have time to add it, let me know and if it's ok with you I can submit a PR with the change.

Have a great day,
Adi Ulici

**Comment by pawelgrzybek** [comment]
Hi.

Really good subject you just stared Sir. Let me elaborate a bit…

This is not in a public docs (yet) because this method needs a little bit of love. I have tons of ideas how to make it more efficient than the current implementation. This use case is very rare and you are probably second if not the first person who came across this need.

I am more than happy to add it to docs when the API is optimised for performance - I would drop an update maybe next week if I have some time. I wont change the name of a method tho — `resizeHandler` keeps the naming convention for all the events and follows the same pattern — {eventname} + Handler. For example `mousemoveHandler`, `clickHandler`, `mouseupHandler` etc. i may consider creating an alias tho :)

Stay tuned Sir and thanks for suggestion. For know let me keep it hidden from public and I will add it at the right time :) Have a great weekend.

**Comment by adiulici** [comment]
Hey,

Thanks for the quick reply. Your points make sense, so I'll keep on using it as is for now, without being afraid that it's going to magically vanish in the near future :) I'd keep my position on recommending an alias, though, just because having methods called `eventHandler` in the public API seems strange.

Thanks again and have a great day!
