### ISSUE TITLE
Electron integration bugs out initially

### ISSUE THREAD

**Issue by HayateLaTech** [pawelgrzybek/siema#175]
Hi,

i'm currently building an electron app and i want to use siema to create some sliders in it, containing pictures - so there is no special thing related on how i try to implement it, it's just some basic generation of a div containing \<img\> tags with some pictures so that it looks like in the examples:

```
<div class="siema">
  <div><img src=""></div>
</div>
```

Now when i try to call a new Siema() with the selector pointing to that div it does manipulate the DOM to create the siema specific element look around that div BUT i get the following problems:

* the div with the class siema is width: 100% and text-align: center - the initial screen i get positions the first element in the slide to the very left of the screen for some reason tho
* if draggable is activated it just doesnt work - i can click and drag the initial picture and move it but it wont go back or to the next slide for some reason

This problem can be fixed tho if i resize the app window.. like.. it works flawlessly after i maximize the window or make it smaller.. initially it just bugs out ;-;

Help me person on Github, you’re my only hope.

**Comment by pawelgrzybek** [comment]
Hi.

I don't have any experience in building electron apps but from everything that you just explained for me it is looking like a problem with execution order. Siema is built purely to work smoothly in the browser — and it does work well here.

I don't really know what are the differences between browser and electron, but assuming that it is running JavaScript (and I know it does) and using HTML and CSS as a building and layout blocks (and I know it does) there must be some issue with a rendering and function execution order. Please make sure that when Siema is initialised it triggers its functionality on a markup that is already on the DOM (or browsers DOM equivalent).

I will close this issue because it is not related with Siema, more with understanding of Electron environment but I am more than happy to follow up on this discussion.

Thanks a lot for contribution 👋

**Comment by HayateLaTech** [comment]
I think i found the error that led to the problem ;-;

So i thought that it'd be okay to integrate js into electron apps via \<script\> tags BUT these scripts arent injected in the renderer process then (this way works for scripts like jquery but not for siema for example) - for that you'll need to inject the scripts via require so i ended up integrating the siema script via

```
var Siema = require('./siema.min.js');
```
and it is working, atleast on a test project - i'll check later if it does work with my other project too but for now i think that's the trick behind this ^^

thanks for the fast response btw and yes - it's actually not directly related to siema but with electron ;-; so sorry for that

**Comment by HayateLaTech** [comment]
Okay nvm, that wasnt actually the problem x3

The problem here was that i was actually using the `new Siema()` on a div that was still hidden (say `display: none`)

So after i used siema on the div AFTER i put it back on the screen (say `display: block`) it works flawlessly ;-;
