### ISSUE TITLE
The `loop` option doesn't actually "loop the slides around"

### ISSUE THREAD

**Issue by liranh85** [pawelgrzybek/siema#183]
I'll start off by thanking you for creating a wonderful component with fantastic documentation - well done!

Now for the issue at hand: The documentation for `loop` writes: "Loop the slides around (example).", but:

- Using this option doesn't actually auto-play the carousel as expected
- The codepen in [the link provided](http://codepen.io/pawelgrzybek/pen/zwOrKN) doesn't actually auto-play the carousel either.

In the [codepen example](http://codepen.io/pawelgrzybek/pen/MbPbLM) you've provided in the issue ["Auto-Start / Rotate #9"](https://github.com/pawelgrzybek/siema/issues/9), you've written custom code to make the carousel auto-play. In that case:
- What is the point of the `loop` and `duration` options? Do they actually do anything?
- Why not make this work out of the box by just specifying `loop` in the options, without any additional code?

**Comment by liranh85** [comment]
I now understand that:
- `loop` does not auto-play the carousel, but rather just makes calling next() on last slide start from beginning
- `duration` is not for auto-play, it is the animation duration when clicking next()

Nonetheless, I would suggest that you make the following changes:
- Make the documentation for `loop` clearer, as I understood it to be essentially auto-play
- Add a new option auto-play, as I can imagine it's a popular use-case

Thank you!

**Comment by lucvanloon** [comment]
You can find an autoplay example here: https://codepen.io/pawelgrzybek/pen/MbPbLM

**Comment by liranh85** [comment]
@lucvanloon, I know, I've actually referenced this codepen in the issue's first comment. What I'm suggesting is to make this functionality come "out of the box" with Siema, as it is a common use case, and would thus save time for a lot of developers by not needing to extend the Siema class.

**Comment by pawelgrzybek** [comment]
Hi.

Thanks for contribution here. When I created Siema I wanted to create two things:

1. Do the math for you.
2. Provide API that will let you do XYZ

It was my intention to force people to use a little bit of simple JS and powerful Siema API to create a feature that suits a project. I really want to keep it that way and keep the code base super tiny as it is. I am not planing to add any automation that can be done in 5 lines of code in a project — to add it to Siema prototype it would be much more lines of code because you need to take into consideration all the other options / methods and handle some collisions.

Hopefully my reasoning makes sense and you you still like Siema.

Have a great day guys! 👋

**Comment by liranh85** [comment]
Fair enough Pawel, thanks for explaining your reasoning.
