### ISSUE TITLE
How do I vertical align an image?

### ISSUE THREAD

**Issue by UndergroundLabs** [pawelgrzybek/siema#201]
The CSS that this library injects into the HTML via the style attribute is messy. It makes it very difficult to style those elements. In my example I want to vertical align an images in a carosel.

How can I do this? It might be better to remove floats and replace with flexbox as it will give users a lot more felxibility and freedom. Ditch the style attributes and include a `.css` in the library that can be imported using whatever CSS processor.

**Comment by pawelgrzybek** [comment]
Hi.

Thanks for voicing your opinion but I have to disagree with you. Flexbox doesn't have that browser support as regular floats have, thats why I use floats one this one. Good info for you — next big release will be build with flexbox.

It is one of the things that users like the most about Siema that it does CSS via JS, so they don't need to care about any other resources. It reduces a server hits by one too. If you are fighting with CSS added by Siema you will probably break something in Siema functionality.

How to vertically align image? It is not a question to Siema author — it is more a question to MDN and CSS spec.

Thanks for input and have a great day :)

**Comment by UndergroundLabs** [comment]
Flexbox has full browser support https://caniuse.com/#feat=flexbox

I know how to vertically align, the problem is you're including the styles directly on the element itself. This is bad practice and makes life harder for developers.

**Comment by UndergroundLabs** [comment]
And seriously, a single server hit is nothing dude.

**Comment by pawelgrzybek** [comment]
You are missing the point. My concern is not a single server request but convenience and ease of use.

**Comment by UndergroundLabs** [comment]
That's the goal of many libraries, but at the moment the way the library works hinders development and results in messy CSS. The style attributes are at the top of the specificity list so to override the styles one has to use `important` which enforces bad practices. It also requires some messy CSS to select the required elements as you apply no classes to the carousel elements.

If you replaced the floats with flexbox (which also supports vertical carousel) and add classes to the elements it would give a lot my styling control.

**Comment by pawelgrzybek** [comment]
If you need to edit markup added by Siema, you are probably doing something wrong and you will definitely break carousel.

Sorry but GitHub is not a place for it. If you want to carry on this conversation, submit PR with suggested approach. For now, have a nice day.

By the way, taken from the Siema website…

> Siema’s purpose is to provide a basic carousel tool and allow developers to extend it by using the available methods. It doesn’t come with any complex configuration and myriad options — I would like to keep it this way. If you need a more powerful library I recommend the amazing Flickity by David DeSandro or Swiper by iDangero team.

**Comment by UndergroundLabs** [comment]
I didn't say I needed to edit the markup. But one would certainly need to modify the CSS. Let me give you an example. Say you want a carousel to show brand logos of partners, clients etc. This is very common. Some logos are icons, others are text based. For example Amazon's logo, vs. Starbucks logo. If you place the Starbucks logo next to the Amazon logo it looks terrible. Vertical entering is required.

Exactly the problem I had. I don't require a solution because I solved it by editing Siema and replacing a few things so it renders a flexbox instead of floats and it doesn't modify the attributes. Works perfectly and gives me a far superior set of layout functionality without dealing with hacky floats - which are btw now bad practice for what you're attempting.

And sorry, I disagree, this is a perfect place to discuss such problems. The library is now dated and should be updated to the correct way of creating a row of items ... which is to use flexbox. The end user of your library benefits and it's updated to current standards.

>  allow developers to extend it by using the available methods.

Here you see the importance of allowing developers to extend. They could extend it a lot more using plain CSS if you was to implement flexbox.

I'm honestly not trying to be a dick, but I feel you're brushing this off as something that's not important. I will spend the weekend writing some test and I'll submit a PR. After all it's your project, but I'm just one user sharing the frustrations I had with your library. That should be taken as feedback not criticism.

**Comment by pawelgrzybek** [comment]
> ...without dealing with hacky floats - which are btw now bad practice for what you're attempting because flexbox is well supported

I used floats because it offers a better support.

As I mentioned earlier, next version of Siema will be build on top of Flexbox. The main reason is not a flexbox, but I want to remove lots of code related with transitions and transforms that will reduce the codebase by half. I totally understand your need of Flexbox in this case. Until now I recommend adding few lines of JS to `onInit` callback instead of doing anything to CSS added by Siema.

> And sorry, I disagree, this is a perfect place to discuss such problems. The library is now dated and should be updated to the correct way of creating a row of items ... which is to use flexbox. The end user of your library benefits and it's updated to current standards.

Again. It is a not an incorrect way — it is better supported one.

> Here you see the importance of allowing developers to extend. They could extend it a lot more using plain CSS if you was to implement flexbox and remove those dirty inline style attributes.

I am using plain CSS :-) again, inline styles are needed for Siema to work. No-one should edit these styles. Never use `!important` please. By "extending" I mean extending a prototype to add functionality. Something that you are trying to do can be done in 3 lines of JS. Extending... `class ExtendedSiema extends Siema { ... }`. You get it?

> That should be taken as feedback not criticism and I apologies if I come across as being a dick. Your library is good, but I see a few areas that could improve it more.

It is a feedback and I fully appreciate it. I am more than happy to review your PR whenever its ready. As I said, `flex` based Siema is ready on my hard drive but I just don't have time to release it now because there is tons that needs to be done.

Some news in Siema 2.0:
- Flexbox based markup (inline styles —  no external CSS stylesheet)
- TypeScript
- E2E
- Auto height param
- ARIA done right

By the way: Don't use carousels. It is a bad UX pattern :)

Ps. We live very close to each other and I am regularly in Birmingham. We may carry on one day with a pint @UndergroundLabs
