### ISSUE TITLE
How to add class to the active item?

### ISSUE THREAD

**Issue by vakulesh** [pawelgrzybek/siema#21]
First of all, thanks for Siema, cool carousel.

I'm not a profi in js, maybe you can tell me how  to add class to the active item?
Thanks.

**Comment by pawelgrzybek** [comment]
It isn't impossible to do with this version but it definitely won't be the nice looking solution. Thing that I will deliver with next version on Siema are basic callbacks that will make it extremely easy to add bunch of new features — active class is one of them.

Be patient, I will keep this issue open and I will let you know when its ready. Thanks for reporting an issue and for contribution into my project.

Have a great day!

**Comment by EugeneSnihovsky** [comment]
+1
Great repo. This is the simplest and coolest carousel I've ever seen.

Waiting for next release with callbacks. Then are very important for develop.

P.S: also  [optional] buttons for quick navigation would complement the project well. 

![Buttons example](https://sc-cdn.scaleengine.net/i/abd04ba95d76d0ef240045e9e1d42928.png)

**Comment by pawelgrzybek** [comment]
Hi @EugeneSnihovsky. Callbacks will improve project a lot (to come in next version). Dots and arrows are easy to add in current version of Siema. Here are examples: 

http://codepen.io/pawelgrzybek/pen/xRWEpR
http://codepen.io/pawelgrzybek/pen/aBQxOw

Wait for the next update, it will make working with Siema much easier.

**Comment by EugeneSnihovsky** [comment]
Thanks for examples, but without callback I can't mark dot link as active. So I will wait for next release :)

**Comment by cannap** [comment]
@EugeneSnihovsky  http://codepen.io/cannap/pen/xgEepm

**Comment by JulienJo** [comment]
Hi!
+1 for the active class - even in auto play mode-!

**Comment by afmarchetti** [comment]
Hi guys, current version have dots with active class? Thanks 😉

**Comment by pawelgrzybek** [comment]
Nope, it is just API and you can build it yourself easily. Thats the core  principal of Siema :)

**Comment by hedleysmith** [comment]
I couldn't get the codepen posted previously to work, here's what I came up with instead: https://codepen.io/anon/pen/oQBdez

It doesn't work when swiping between slides though at the moment.

**Comment by nikola-wd** [comment]
This is precisely what I needed, I have been using swiper for my website [https://www.webredone.com/](https://www.webredone.com/) , but that library added about 200KB to the page size that I wanted to minimize to get better load speed scores. This is how I did it (Works ok, but only when you click on button it doesn't restart after some time, it only restarts after you hover on / off the slider itself, I couldn't get it to have a consistent 1s delay after clicking button - it continued speeding up the slides changing, most probably due to me still not understanding closures (setTimeout) that much. Maybe someone could improve this one to restart after clicking on button (after a delay, not instantly))
[https://codepen.io/nikola_wd/pen/exwbgg](https://codepen.io/nikola_wd/pen/exwbgg)
