### ISSUE TITLE
Object.assign

### ISSUE THREAD

**Issue by kaizer1v** [pawelgrzybek/siema#226]
https://github.com/pawelgrzybek/siema/blob/9534e7b73f403a3720045243a4eaa6d5a6fb06b9/src/siema.js#L64

Why not use `Object.assign` here instead?

Here's the [compatibility chart](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility)

**Comment by pawelgrzybek** [comment]
Hi.

Few years back when I created Siema I experienced some issue with using this one with babel. It probably changed now, but I cannot be bothered to change it now because it is working just fine and I am not actively maintaining this project anymore. I am actively looking for contributors who can pick this one up and align with my expectations for the future development (accessibility, typescript, ux-focused).

Thanks for pointing out tho.

**Comment by kaizer1v** [comment]
Would love to help / collaborate. I am learning things myself :+1:
