### ISSUE TITLE
Issue with IE 11

### ISSUE THREAD

**Issue by pulkaproffs** [pawelgrzybek/siema#242]
Hi. Great slider! I know its discontinued, but hopefully someone reads this and can figure out whats wrong. 

Im trying to implement the slider for our e-commerce store, and as far as I know, the slider works great in all browsers and versions its intended for, except with IE11. Edge works fine though. What happens is that the slider doesnt seem to initiate, and the images just stack on top of each other as a column, in their original size. Theres a live example of it here: https://www.nameon.no/slidertest. The slider is at the bottom of the page. Appreciate any help I can get. Thanks :)

(Need to mention that im a novice on javascript)

**Comment by paytonbox** [comment]
It doesn't appear to be a problem with the plugin, but rather a syntax error in your code. IE 11 doesn't support using arrow functions.
```prev.addEventListener('click', () => mySiema.prev());
next.addEventListener('click', () => mySiema.next());```

You can either swap the arrow functions for standard ones, or use a compiler like babel to convert your javascript down to es5 so that older browsers can read it.

**Comment by pawelgrzybek** [comment]
Hi @pulkaproffs, read here ☝️
Thanks @paytonbox 

Have a lovely day y'all 🥑

**Comment by pulkaproffs** [comment]
Ok, thanks for the response and help. You really helped me out a lot there. Have a nice day :)
