### ISSUE TITLE
Update / Re-render slides method

### ISSUE THREAD

**Issue by sorodrigo** [pawelgrzybek/siema#26]
Hi! I've been using Siema for a Vue.js project and I have to say it's pretty useful. Recently I ran into a problem when trying to load the slides dynamically. I managed to fix the issues, but my solution is far from elegant.
[See example](https://github.com/Vizzuality/DATA4SDGS-Highway/blob/72a9c2e174dc574d7a347d66255eaf26bbc4e45b/app/scripts/components/Slider/index.vue#L11)

**My problem**
Slides are loaded asynchronously, so the Siema object is already rendered when the slides arrive.

**My solution**
Render an empty Siema object and when the async slides arrive, destroy the object and create it again.

**Proposal**
It would be useful to have a method to recalculate the slides instead of deleting and creating.

Thanks in advance!

**Comment by pawelgrzybek** [comment]
It is a great idea. As long as your solution works great keep on doing it. It is on my roadmap to create `destroy()` method that reverts the markup and removes all event listeners and `update()` that builds it again and attaches all events.

**Comment by pawelgrzybek** [comment]
Actually the `update()` method will do exactly the same as your `renderSiema()` from your example @sorodrigo. I agree that would be nice to have it available as a part of API.

**Comment by sorodrigo** [comment]
The thing is that inside the `renderSiema()` I always reinstantiate Siema. I would see more fit for an `update()` method, using only one instance instead, and recalculating the children slides.

**Comment by pawelgrzybek** [comment]
I'll do my best to add this functionality soon. Thanks for suggestion.

**Comment by powerbuoy** [comment]
Also loving Siema, but having the same issue. The problem is that calling `destroy()` doesn't seem to revert the HTML at all, so running Siema again doesn't work as the markup has changed... (Siema now runs on its own wrapping `div` element as opposed to the original children of the slideshow element).

The reason I need this is because my slideshow changes width on user actions but the slides stay the same width :/

**Comment by sorodrigo** [comment]
@powerbuoy Idk if I understood you correctly but: currently if you run `destroy()` only the event listeners are removed, thus making it imposible to adjust the width.

**Comment by powerbuoy** [comment]
Yea, that's it, it doesn't revert the HTML (there is still a div in there that wasn't there before running the slideshow) so running the slideshow again after destruction doesn't work.

An update method that recalculates the bounding client rect would be ideal imo.

**Comment by sorodrigo** [comment]
Agree, for now I recommend you to remove the container's children. Then reinstanciate.

**Comment by pawelgrzybek** [comment]
Hi. Few things are coming with in a new version:

- `destroy()` - removes active listeners and reverts the initial markup
- `init()` - which is exact opposite to `destroy()`
- `update()` - recalculate sliders value when some items are added

Thanks guys for all suggestions. I know that the current methods set isn't enough to handle all situations. I'll do my best to add some flexibility but still keep it lightweight and neat.

Have a great day people 🤗

**Comment by powerbuoy** [comment]
Looking good! One question though; today Siema already has support for recalculating the slide width on windows resize, however, if the actual browser doesn't resize but just the slideshow element this calculation never happens (because I assume it happens on the window.resize event).

Is there a way for me to call the same method as you do on window.resize? I found something called `resizeHandler()` but simply calling that doesn't seem to help.

**Comment by pawelgrzybek** [comment]
I see — it is an edge case tho. Thats true, resizeHandler is triggered on windows resize only at this moment. Adding a native listener to element without chunky scripts is possible but isn't well supported unfortunately. Triggering `resizeHandler()` should do the job actually, have a look at this example that I just added to collection on Codepen...

http://codepen.io/pawelgrzybek/pen/zNZEZJ

**Comment by powerbuoy** [comment]
I agree you should _not_ add a check for if the slideshow changes width, that's better handled by us users imo (since we know exactly when it might change).

Using `resizeHandler()` worked perfectly though so thanks. Looking at the code, it almost seems like that method can be used for sorodrigo's issue as well as it calls `this.resolveSlidesNumber();` before re-calculating the slide width? In other words, you already have an `update()` method.

**Comment by sorodrigo** [comment]
Thanks but won't help me cause `resolveSlidesNumber()` only recalculates the perPage slides, doesn't check if there are new child elements.

**Comment by pawelgrzybek** [comment]
Thats correct @sorodrigo . Only full `destroy()` and `init()` will help here — to come with next version. `resizeHandler()` kind of does the good job at this moment imho.

What do you guys think about adding method to add new slide and remove one? For example...

`mySiema.addSlide(index = lastSlide)`;
`mySiema.removeSlide(index)`;

Maybe thats the better solution to handle edge cases discussed in this issue?

**Comment by pawelgrzybek** [comment]
Hi guys. It's been a while :)

Just released version 1.4.0 that solves the problem that we were chatting about above. Thanks a ton for your contribution and very valuable suggestions.

https://github.com/pawelgrzybek/siema/releases/tag/v.1.4.0

Thannks 🥑

**Comment by chadsteele** [comment]
I'm looking for the update() method.  It's not in the current release.  :(
https://github.com/pawelgrzybek/siema/issues/210#issue-355849574

**Comment by johannesjo** [comment]
What works for me is just calling the `resizeHandler()` method.
