### ISSUE TITLE
Dafuq are your talking about...anti-pattern...pff, stfu and do updates

### ISSUE THREAD

**Issue by saint777** [pawelgrzybek/siema#289]
----

**Comment by panoply** [comment]
This shit really bugs me tbh. 

Like, the sheer audacity of the above user is utterly bewildering to me. @pawelgrzybek can do whatever the fuck he wants to do with this package and he is entitled to his own opinion. Regardless of where one sits on the subject of whether carousel components are an anti-pattern or not it is no excuse for you @saint777 to submit this issue demanding activity from the maintainer. It is fucking insufferable to be honest.

A lot of folks don't agree with the anti-pattern position and many would love to see Siema live on but do you see any of us demanding or submitting issues of this nature? No, because we are fucking adults and this is open source. Take your childish and immaturity elsewhere.

Apologies to anyone subscribed or watching this project that was subject to this.

**Comment by pawelgrzybek** [comment]
@saint777 you just gave me an idea for a new post on my blog, stay tuned. Thank you 🤗

**Comment by saint777** [comment]
> @saint777 you just gave me an idea for a new post on my blog, stay tuned. Thank you 🤗

hey man, i only wanted to motivate you, that's it

**Comment by saint777** [comment]
> This shit really bugs me tbh.
> 
> Like, the sheer audacity of the above user is utterly bewildering to me. @pawelgrzybek can do whatever the fuck he wants to do with this package and he is entitled to his own opinion. Regardless of where one sits on the subject of whether carousel components are an anti-pattern or not it is no excuse for you @saint777 to submit this issue demanding activity from the maintainer. It is fucking insufferable to be honest.
> 
> A lot of folks don't agree with the anti-pattern position and many would love to see Siema live on but do you see any of us demanding or submitting issues of this nature? No, because we are fucking adults and this is open source. Take your childish and immaturity elsewhere.
> 
> Apologies to anyone subscribed or watching this project that was subject to this.

wow, "childish and immaturity" "insufferable"
