### ISSUE TITLE
Hiding Previous and Next button

### ISSUE THREAD

**Issue by geekysneaks** [pawelgrzybek/siema#47]
I was wondering if there is a way to hide the prev button on the first slide and hide the next button on the last slide.

**Comment by pawelgrzybek** [comment]
Hi.

Because the prev and next arrow don't come out of the box it requires to extends a prototype with a custom method to add them. Hiding arrow dependable of the slide purely depends of the custom implementation. Recently added callbacks in version 1.3.0 can hep with it a lot. Have a look at CodePen collection where I present how to build arrows, and add a bit of logic on top of it.

Thanks and have a great day 🥑

**Comment by geekysneaks** [comment]
Is there a way to detect the first and last slide

**Comment by pawelgrzybek** [comment]
Of course my friend. Have a look at the public methods and properties tha Siema gives you to. That is the nsippet that you are asking for 😁

```js
const mySiema = new Siema();

if(mySiema.currentSlide === 0) {
    console.log('Hello, I am first slide');
}

if(mySiema.currentSlide === mySiema.innerElements.length - 1) {
    console.log('Hello, I am last slide');
}
```

Thanks 🥑

**Comment by MinSomai** [comment]
here's a codepen where I implemented this functionality, multiple sliders and using a single function
[https://codepen.io/minsomai/pen/wvKzEWG](https://codepen.io/minsomai/pen/wvKzEWG)
