### ISSUE TITLE
Using the parent element rather than window.innerWidth for resolveSlidesNumber()

### ISSUE THREAD

**Issue by babysteps** [pawelgrzybek/siema#56]
Hello,

Just a suggestion, but not every use case for a carousel is the entire width of the viewport.  In the `resolveSlidesNumber()` function, it would probably be better to use the parent element's width, rather than window.innerWidth.

**Comment by pawelgrzybek** [comment]
Hi.

Thanks for suggestion. I know that the element media queries are a hot thing now (and this is good) and it makes lots of sense to change slides number by carousel width instead of the window...

There is one issue with that — majority of people expect to work with carousel exactly in the same way as they work with CSS media queries. Changing that could be very confusing. 

For the time being I'll be stick to current solution and maybe at some point...

Thanks and have a great weekend 🍻

**Comment by babysteps** [comment]
Thanks for the response.  One other thing I noticed was that you have a `resize` listener, but not an `orientationchange` listener for mobile.

Have a great weekend as well :)
