### ISSUE TITLE
Fixed width slides?

### ISSUE THREAD

**Issue by 2kool2** [pawelgrzybek/siema#59]
Hi, nice and light just the way I like it. Good work dude.

Is it possible to somehow have fixed width slides and align centre?
So a portion of the previous and next slide is also displayed.
The wider the viewport, the more slides displayed.
Like this: https://www.tesco.com/mothers-day/#carousel-personal
The UX fellahs say seeing a partial encourages interaction more so than just buttons.

**Comment by pawelgrzybek** [comment]
I see. I'm so sorry but at this moment Siema is not able to do it without some horrible not worth it tricks. It is light and simple carousel mechanism but unfortunately it has it's own restrictions :( Sorry about it.

Have a great day 🥑

**Comment by 2kool2** [comment]
Thanks for the response.
Do you mind if I download a copy and see  what I can rework?

**Comment by pawelgrzybek** [comment]
Yeah feel free to play around. If your solution is nice and clean I may ever merge it with core of a Siema script.

Have a great day.

**Comment by TheMangoTrain** [comment]
I too am interested in such a feature!

From a UX stand-point, it does encourage interaction. Right away it informs the user that more slides are available. This makes it possible to not have arrows and dots for a simpler interface, because the sense of direction and knowing-about-more-slides comes automatically by seeing adjacent slides peaking out from the sides.

This would in effect make it more like a carousel. A slider is usually single sheets of slides shown at a time, whereas a carousel shows a slides in a series or continuum.
