### ISSUE TITLE
Batch updates

### ISSUE THREAD

**Issue by globeport** [pawelgrzybek/siema#64]
Hi thanks for developing this.

I noticed that you call the UpdateFrame function whenever the collection of slides is changed. There must be a significant performance hit associated with this. I wondered if you would consider altering the api to allow batch updates. e.g. append([slide1, slide2], callback). with UpdateFrame being called only once.

Thanks,
Stuart

**Comment by pawelgrzybek** [comment]
Hi @globeport.

This "significant performance hit" is probably tiny exaggeration but you are totally right! It can be improved and it is actually very easy. I will drop this improvement with bunch of cool new stuff with next update to 1.5. It is a fantastic idea to add option to add multiple slides in an array instead of recalculating everything every single insertion.

I'm happy that you found my library worth spending time with and using.
Thanks for suggestion and have a fantastic day.

**Comment by globeport** [comment]
Thankyou very much :) yeh,bit of an exaggeration but I'm dropping this thing in a news feed item so it makes sense to think about performance when potentially scrolling through lots of them.

**Comment by pawelgrzybek** [comment]
Totally! Stay tuned! 1.5 is coming :) Thanks again.

**Comment by pawelgrzybek** [comment]
Hi.

I am just finishing a next release. It was a good time for me to review all feature / enhancements requests. The core principle of Siema is to give users enough properties and methods  to accomplish these kind of things via API (your request is a perfect example). Feature that you requested is an edge case and not many users are gonna benefit from added this one to list of methods. Hopefully it makes sense and you get my reasoning why I try to keep API as neat as possible. 

Thanks for using Siema 👋
