### ISSUE TITLE
Is there an option to use dot for carousel ?

### ISSUE THREAD

**Issue by rainstormza** [pawelgrzybek/siema#73]
Is there an option to use dot for carousel ?

![image](https://user-images.githubusercontent.com/4003032/29327697-2d533768-821a-11e7-9363-0dac8c8255f5.png)

thanks

**Comment by pawelgrzybek** [comment]
HI.

Nope, but on CodePen collection you can find an example how to do it with ease via available API.

Thanks and have a great day 🥑

**Comment by leahprin** [comment]
@pawelgrzybek do you have a link? I can't seem to find it in your codepen collection... 

Thanks!

**Comment by pawelgrzybek** [comment]
https://codepen.io/pawelgrzybek/pen/aBQxOw

**Comment by leahprin** [comment]
Yep, saw that one. I wasn't sure how to translate that into the typical dot design
![image](https://user-images.githubusercontent.com/22362871/31951705-93ba8cd0-b92a-11e7-98be-86d4e9ead5ce.png)

https://stackoverflow.com/questions/46913638/siema-ca-indicator?noredirect=1#comment80775193_46913638

**Comment by leahprin** [comment]
You are the best! I'm sure it's a fairly common query, so no doubt it'll be helpful for others. Been scratching my head for a while on this one...

**Comment by pawelgrzybek** [comment]
Boom 💣

https://codepen.io/pawelgrzybek/pen/boQQWy

I put lots of comments to explain what is going on. Hopefully it helps.

**Comment by leahprin** [comment]
Amazing! The comments are super helpful. Thank you so much.

**Comment by thewebprojects** [comment]
Thanks for sharing Siema.  I appreciate these solutions. Instead of offering everything and the kitchen sink which lead to bloat, we're given the essentials, a foundation to build upon.  It's great. 

I can't seem solve a simple problem/challenge.  Admittedly I'm not up to par on JS so what may be obvious is escaping me. I want the slides to be a equal height and I want to position the pagination buttons above the slides (e.g. higher z-index).  Any insight?

**Comment by pawelgrzybek** [comment]
Ooo hi!

Thanks for nice words about Siema! I'm really glad that you enjoying using it.

Your question is actually more CSS than JS related. I just created a full solution for you. I'm sure you will be able to understand what is going on. I put tons of comment in the code to help you to understand what is going on.

https://codepen.io/pawelgrzybek/pen/LeZXBx

Have a lovely day @thewebprojects !

**Comment by thewebprojects** [comment]
Excellent.  Thanks!

**Comment by thewebprojects** [comment]
How would I apply options such as loop: true, etc. based on this example?

**Comment by pawelgrzybek** [comment]
Hi.

```js
new SiemaWithPagination({
  loop: true,
  onInit() {
    this.addPagination();
  }
})
```

:)

**Comment by thewebprojects** [comment]
Do I need to include the smiley face in my script? Ha. Kidding. Thanks. This is my new goto boilerplate for carousels.

**Comment by pawelgrzybek** [comment]
Thanks a ton for using Siema! Have a lovely day and merry christmas :)

**Comment by euene** [comment]
https://github.com/pawelgrzybek/siema/issues/73#issuecomment-339039291

Thanks for providing the codepen for the dots class, but it seems to have some issues with the perPage and loop settings. 

Example test case: 
https://codepen.io/anon/pen/BPwQRQ

1. When both perPage is showing multiple slides and loop is set to true, the active state won't be applied to the last few dots/slides but everything otherwise works OK. 

2. When there is just the perPage setting but no loop, the last dots/slides are unreachable.

**Comment by euene** [comment]
@pawelgrzybek 

https://github.com/pawelgrzybek/siema/issues/73#issuecomment-339039291

Thanks for providing the codepen for the dots class, but it seems to have some issues with the perPage and loop settings. 

Example test case: 
https://codepen.io/anon/pen/BPwQRQ

1. When both perPage is showing multiple slides and loop is set to true, the active state won't be applied to the last few dots/slides but everything otherwise works OK. 

2. When there is just the perPage setting but no loop, the last dots/slides are unreachable.
