### ISSUE TITLE
Not working with ng-repeat on angularjs 1.6.6

### ISSUE THREAD

**Issue by hernimen** [pawelgrzybek/siema#91]
Issue description:  
I'm using Pug and  the last version of Siema.
When I'm trying to make an ng-repeat of a component It doesn't work.

```
.siema
	div(ng-repeat="suggestion in $ctrl.suggestions")
		suggestion(suggestion="suggestion")
```
but if I write
```
.siema
	div
		p hello	
	div 
		p hello
	div 
		p hello

```
It works.
Thx

**Comment by pawelgrzybek** [comment]
Hi.

Thank for reporting an issue with your project. I'm afraid that this is not related with Siema. I cannot help you with this one because I don't know Angular at all.

I assume it is related with an order when Siema is instantiated and when Angular builds the actual markup. Please play around with component lifecycle hooks on your project to make sure that the Siema is initiialized when the markup is ready.

Sorry for not being super helpful today.

**Comment by hernimen** [comment]
ok! thanks anyway

**Comment by CristalT** [comment]
The problem is tha Sieme initialized before AngularJS can obtain the data from API.

I found a simple solution to the same Issue, just in case someone is looking for something similar.
I created a directive where init Siema:

`app.directive('siemaCarousel', () => {
    return {
        restrict: 'E',
        templateUrl: 'templates/carousel.html',
        scope: {
            data: '='
        },
        link: function (scope) {
            let siema;
            scope.$watch('data', function(value) {
                if(value.length) {
                    siema = new Siema({
                        selector: '.carousel',
                        duration: 500,
                        loop: true,
                        easing: 'ease-out'
                    });
                }
            })

            scope.goPrev = function () {
                siema.prev();
            };

            scope.goNext = function () {
                siema.next();
            };
        }
    }
});`

The `scope.$watch` are watching for changes in dinamic data. There is the solution for async data obtained by `$http` service. 

The HTML template could be something like this:

`<div class="carousel-container">
  <div class="carousel">
    <div ng-repeat="item in data"><img src="{{ item.image }}"></div>
  </div>
  <div class="carousel-controls">
    <button class="prev-button" ng-click="goPrev()"><i class="glyphicon glyphicon-chevron-left"></i></button>
    <button class="next-button" ng-click="goNext()"><i class="glyphicon glyphicon-chevron-right"></i></button>
  </div>
</div>`

And you may call this directive as well:

`<siema-carousel data="carousel"></siema-carousel>`

Where `data` may have the array obtained from the $http service o any API interface.

**Comment by zsslovelyg** [comment]
.siema
	div(ng-repeat="suggestion in $ctrl.suggestions")
		suggestion(suggestion="suggestion")

setTimeout about 200ms. It worked for me
