### ISSUE TITLE
[bug] Prev / next buttons eventListeners are not removed after destroy()

### ISSUE THREAD

**Issue by ChrisPlaneta** [pawelgrzybek/siema#96]
Hi,

I've found 2 bugs in Siema. The Other one will be posted in a new thread.

Do this:
- create a new Siema,
- attach next/prev events to it
- destroy Siema with destroy(true), 
- recreate a siema with the same var name
- reattach next/prev events

After you do this, clicking on next/prev buttons will move 2 slides. When you do this multiple times, clicking on siema will also move slides by this number.

Have a nice day,
Krzysztof

**Comment by pawelgrzybek** [comment]
Hi.

This is totally expected behaviour. Because Siema doesn't come with next / prev buttons, user have to create them and attach listeners. The `destroy()` method gives you a callback tho — use it to remove listeners from next / prev buttons. Like so:

https://codepen.io/pawelgrzybek/pen/mBKXPa

Thanks and have a great day 🥑
